# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zUqfOH35AYpLsHazH8Rk2qUo_xBwKHcW
"""

import os
import pickle
from tensorflow.keras.models import load_model

# Load the trained model
model = load_model('bcd_model.h5')

# Save the model using pickle
with open('bcd_model.pkl', 'wb') as f:
    pickle.dump(model, f)

# Load the model using pickle
with open('bcd_model.pkl', 'rb') as f:
    loaded_model = pickle.load(f)